In [2]:
import pandas as pd
import numpy as np

In [3]:
# Membaca Dataset

df = pd.read_csv('creditApprovalUCI.csv')
df.head()

  A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15  A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  202.0    0    1
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g   43.0  560    1
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  280.0  824    1
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  100.0    3    1
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  120.0    0    1

In [4]:
# Melihat Informasi Dataset

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A1      690 non-null    str
 1   A2      690 non-null    float64
 2   A3      690 non-null    float64
 3   A4      690 non-null    str
 4   A5      690 non-null    str
 5   A6      690 non-null    str
 6   A7      690 non-null    str
 7   A8      690 non-null    float64
 8   A9      690 non-null    str
 9   A10     690 non-null    str
 10  A11     690 non-null    int64
 11  A12     690 non-null    str
 12  A13     690 non-null    str
 13  A14     690 non-null    float64
 14  A15     690 non-null    int64
 15  A16     690 non-null    int64
dtypes: float64(4), int64(3), str(9)
memory usage: 86.4 KB

In [5]:
# Melihat Tipe Data

df.dtypes

A1         str
A2     float64
A3     float64
A4         str
A5         str
A6         str
A7         str
A8     float64
A9         str
A10        str
A11      int64
A12        str
A13        str
A14    float64
A15      int64
A16      int64
dtype: object

In [7]:
# Menampilkan Kolom Kategorikal

categorical_columns = df.select_dtypes(include='object').columns
print(categorical_columns)

Index(['A1', 'A4', 'A5', 'A6', 'A7', 'A9', 'A10', 'A12', 'A13'], dtype='str')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14948\1739236648.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include='object').columns

In [8]:
# Melakukan One Hot Encoding

df_encoded = pd.get_dummies(df, columns=categorical_columns)

In [9]:
# Melihat Hasil Encoding

df_encoded.head()

,A2,A3,A8,A11,A14,A15,A16,A1_Missing,A1_a,A1_b,...,A7_z,A9_f,A9_t,A10_f,A10_t,A12_f,A12_t,A13_g,A13_p,A13_s
0,30.83,0.000,1.25,1,202.0,0,1,False,False,True,...,False,False,True,False,True,True,False,True,False,False
1,58.67,4.460,3.04,6,43.0,560,1,False,True,False,...,False,False,True,False,True,True,False,True,False,False
2,24.50,0.500,1.50,0,280.0,824,1,False,True,False,...,False,False,True,True,False,True,False,True,False,False
3,27.83,1.540,3.75,5,100.0,3,1,False,False,True,...,False,False,True,False,True,False,True,True,False,False
4,20.17,5.625,1.71,0,120.0,0,1,False,False,True,...,False,False,True,True,False,True,False,False,False,True

In [10]:
# Melihat Jumlah Kolom Setelah Encoding

print("Jumlah kolom sebelum encoding :", df.shape[1])
print("Jumlah kolom sesudah encoding :", df_encoded.shape[1])

Jumlah kolom sebelum encoding : 16
Jumlah kolom sesudah encoding : 52

In [11]:
# Melihat Struktur Dataset Baru

df_encoded.info()

<class 'pandas.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 52 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   A2          690 non-null    float64
 1   A3          690 non-null    float64
 2   A8          690 non-null    float64
 3   A11         690 non-null    int64
 4   A14         690 non-null    float64
 5   A15         690 non-null    int64
 6   A16         690 non-null    int64
 7   A1_Missing  690 non-null    bool
 8   A1_a        690 non-null    bool
 9   A1_b        690 non-null    bool
 10  A4_Missing  690 non-null    bool
 11  A4_l        690 non-null    bool
 12  A4_u        690 non-null    bool
 13  A4_y        690 non-null    bool
 14  A5_Missing  690 non-null    bool
 15  A5_g        690 non-null    bool
 16  A5_gg       690 non-null    bool
 17  A5_p        690 non-null    bool
 18  A6_Missing  690 non-null    bool
 19  A6_aa       690 non-null    bool
 20  A6_c        690 non-null    bool
 21  A6_cc       690 non-null    bool
 22  A6_d        690 non-null    bool
 23  A6_e        690 non-null    bool
 24  A6_ff       690 non-null    bool
 25  A6_i        690 non-null    bool
 26  A6_j        690 non-null    bool
 27  A6_k        690 non-null    bool
 28  A6_m        690 non-null    bool
 29  A6_q        690 non-null    bool
 30  A6_r        690 non-null    bool
 31  A6_w        690 non-null    bool
 32  A6_x        690 non-null    bool
 33  A7_Missing  690 non-null    bool
 34  A7_bb       690 non-null    bool
 35  A7_dd       690 non-null    bool
 36  A7_ff       690 non-null    bool
 37  A7_h        690 non-null    bool
 38  A7_j        690 non-null    bool
 39  A7_n        690 non-null    bool
 40  A7_o        690 non-null    bool
 41  A7_v        690 non-null    bool
 42  A7_z        690 non-null    bool
 43  A9_f        690 non-null    bool
 44  A9_t        690 non-null    bool
 45  A10_f       690 non-null    bool
 46  A10_t       690 non-null    bool
 47  A12_f       690 non-null    bool
 48  A12_t       690 non-null    bool
 49  A13_g       690 non-null    bool
 50  A13_p       690 non-null    bool
 51  A13_s       690 non-null    bool
dtypes: bool(45), float64(4), int64(3)
memory usage: 68.2 KB