In [1]:
# Import Library

import pandas as pd
import numpy as np

In [3]:
# Membaca Dataset

df = pd.read_csv('olympics.csv', header=1)
df.head()

,Unnamed: 0,? Summer,01 !,02 !,03 !,Total,? Winter,01 !.1,02 !.1,03 !.1,Total.1,? Games,01 !.2,02 !.2,03 !.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [4]:
# Melihat Struktur Data

df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      147 non-null    str
 1   ? Summer        147 non-null    int64
 2   01 !            147 non-null    int64
 3   02 !            147 non-null    int64
 4   03 !            147 non-null    int64
 5   Total           147 non-null    int64
 6   ? Winter        147 non-null    int64
 7   01 !.1          147 non-null    int64
 8   02 !.1          147 non-null    int64
 9   03 !.1          147 non-null    int64
 10  Total.1         147 non-null    int64
 11  ? Games         147 non-null    int64
 12  01 !.2          147 non-null    int64
 13  02 !.2          147 non-null    int64
 14  03 !.2          147 non-null    int64
 15  Combined total  147 non-null    int64
dtypes: int64(15), str(1)
memory usage: 18.5 KB

,? Summer,01 !,02 !,03 !,Total,? Winter,01 !.1,02 !.1,03 !.1,Total.1,? Games,01 !.2,02 !.2,03 !.2,Combined total
count,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000
mean,13.476190,65.428571,64.965986,69.795918,200.190476,6.700680,13.047619,13.034014,12.897959,38.979592,20.176871,78.476190,78.000000,82.693878,239.170068
std,7.072359,405.549990,399.309960,427.187344,1231.306297,7.433186,80.799204,80.634421,79.588388,240.917324,13.257048,485.013378,478.860334,505.855110,1469.067883
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.000000,0.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000,0.000000,1.000000,1.000000,2.500000
50%,13.000000,3.000000,4.000000,6.000000,12.000000,5.000000,0.000000,0.000000,0.000000,0.000000,15.000000,3.000000,4.000000,7.000000,12.000000
75%,18.500000,24.000000,28.000000,29.000000,86.000000,10.000000,1.000000,2.000000,1.000000,5.000000,27.000000,25.500000,29.000000,32.500000,89.000000
max,27.000000,4809.000000,4775.000000,5130.000000,14714.000000,22.000000,959.000000,958.000000,948.000000,2865.000000,49.000000,5768.000000,5733.000000,6078.000000,17579.000000

In [5]:
# Melihat Nama Kolom

df.columns

Index(['Unnamed: 0', '? Summer', '01 !', '02 !', '03 !', 'Total', '? Winter',
       '01 !.1', '02 !.1', '03 !.1', 'Total.1', '? Games', '01 !.2', '02 !.2',
       '03 !.2', 'Combined total'],
      dtype='str')

In [6]:
# Mengganti Nama Kolom Pertama

df.rename(columns={df.columns[0]: 'Country'}, inplace=True)

In [8]:
# Membersihkan Nama Kolom

df.columns = (
    df.columns
      .str.replace('?', '', regex=False)
      .str.replace('!', '', regex=False)
      .str.strip()
)

df.columns

Index(['Country', 'Summer', '01', '02', '03', 'Total', 'Winter', '01 .1',
       '02 .1', '03 .1', 'Total.1', 'Games', '01 .2', '02 .2', '03 .2',
       'Combined total'],
      dtype='str')

In [9]:
# Mengecek Missing Value

df.isnull().sum()

Country           0
Summer            0
01                0
02                0
03                0
Total             0
Winter            0
01 .1             0
02 .1             0
03 .1             0
Total.1           0
Games             0
01 .2             0
02 .2             0
03 .2             0
Combined total    0
dtype: int64

In [10]:
# Mengecek Data Duplikat

df.duplicated().sum()

np.int64(0)

In [11]:
# Mengecek Tipe Data

df.dtypes

Country             str
Summer            int64
01                int64
02                int64
03                int64
Total             int64
Winter            int64
01 .1             int64
02 .1             int64
03 .1             int64
Total.1           int64
Games             int64
01 .2             int64
02 .2             int64
03 .2             int64
Combined total    int64
dtype: object

In [12]:
# Menampilkan Data Setelah Dibersihkan

df.head()

,Country,Summer,01,02,03,Total,Winter,01 .1,02 .1,03 .1,Total.1,Games,01 .2,02 .2,03 .2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12