In [1]:
# Import library

import pandas as pd

In [2]:
# Load dataset

df = pd.read_csv('epl-goalScorer(20-21).csv')
df.head()

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796

In [3]:
# Memahami Struktur Data

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    522 non-null    int64
 1   id            522 non-null    int64
 2   player_name   522 non-null    str
 3   games         522 non-null    int64
 4   time          522 non-null    int64
 5   goals         522 non-null    int64
 6   xG            522 non-null    float64
 7   assists       522 non-null    int64
 8   xA            522 non-null    float64
 9   shots         522 non-null    int64
 10  key_passes    522 non-null    int64
 11  yellow_cards  522 non-null    int64
 12  red_cards     522 non-null    int64
 13  position      522 non-null    str
 14  team_title    522 non-null    str
 15  npg           522 non-null    int64
 16  npxG          522 non-null    float64
 17  xGChain       522 non-null    float64
 18  xGBuildup     522 non-null    float64
dtypes: float64(5), int64(11), str(3)
memory usage: 77.6 KB

In [4]:
# Memahami Struktur Data

df.describe()

,Unnamed: 0,id,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
count,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000
mean,260.500000,4380.932950,19.643678,1420.068966,1.862069,2.000806,1.289272,1.376029,17.379310,12.963602,2.061303,0.091954,1.668582,1.821450,5.663368,3.455060
std,150.832689,3281.776121,11.619836,1031.604819,3.338851,3.317946,2.083350,1.886510,21.572664,16.164361,2.203661,0.295800,2.909929,2.931176,5.600249,3.376584
min,0.000000,65.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,130.250000,839.750000,10.000000,470.250000,0.000000,0.074668,0.000000,0.049245,2.000000,1.000000,0.000000,0.000000,0.000000,0.074668,1.191391,0.720353
50%,260.500000,4627.000000,21.000000,1342.000000,1.000000,0.737295,0.000000,0.691122,10.000000,7.000000,2.000000,0.000000,0.500000,0.715585,4.252738,2.656397
75%,390.750000,7690.500000,30.000000,2319.000000,2.000000,2.053378,2.000000,2.050509,23.750000,19.000000,3.000000,0.000000,2.000000,1.945799,8.308002,5.254647
max,521.000000,9552.000000,38.000000,3420.000000,23.000000,22.174859,14.000000,11.474996,138.000000,95.000000,12.000000,2.000000,19.000000,19.130183,28.968234,18.323006

In [5]:
# Memahami Struktur Data

df.columns

Index(['Unnamed: 0', 'id', 'player_name', 'games', 'time', 'goals', 'xG',
       'assists', 'xA', 'shots', 'key_passes', 'yellow_cards', 'red_cards',
       'position', 'team_title', 'npg', 'npxG', 'xGChain', 'xGBuildup'],
      dtype='str')

In [ ]:
# Cek Data Kotor (Data Cleaning)

# Cek missing value

df.isnull().sum()

Unnamed: 0      0
id              0
player_name     0
games           0
time            0
goals           0
xG              0
assists         0
xA              0
shots           0
key_passes      0
yellow_cards    0
red_cards       0
position        0
team_title      0
npg             0
npxG            0
xGChain         0
xGBuildup       0
dtype: int64

In [7]:
# Cek duplikasi

df.duplicated().sum()

np.int64(0)

In [8]:
# Seleksi Data

# Ambil kolom penting

df[['player_name', 'team_title', 'goals', 'assists']]

                player_name         team_title  goals  assists
0                Harry Kane          Tottenham     23       14
1             Mohamed Salah          Liverpool     22        5
2           Bruno Fernandes  Manchester United     18       12
3             Son Heung-Min          Tottenham     17       10
4           Patrick Bamford              Leeds     17        7
..                      ...                ...    ...      ...
517  Jaden Philogene-Bidace        Aston Villa      0        0
518         Gaetano Berardi              Leeds      0        0
519          Anthony Elanga  Manchester United      0        0
520             Femi Seriki   Sheffield United      0        0
521         Tyrese Francois             Fulham      0        0

[522 rows x 4 columns]

In [10]:
# Analisis Sederhana

# Top scorer (gol terbanyak)

df.sort_values(by='goals', ascending=False).head(10)

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796
5,5,5555,Dominic Calvert-Lewin,32,2788,16,18.136449,0,2.101819,82,18,3,0,F S,Everton,16,18.136449,19.698850,4.159406
6,6,755,Jamie Vardy,34,2848,15,19.942946,9,5.087882,82,28,1,0,F S,Leicester,7,13.092427,18.227907,2.412588
7,7,8865,Ollie Watkins,37,3330,14,16.280178,5,5.314029,98,45,2,1,F,Aston Villa,13,14.757840,22.014021,5.334991
8,8,314,Ilkay Gündogan,28,2033,13,9.566883,2,3.816220,54,42,1,0,M S,Manchester City,12,8.044545,19.286812,10.148375
9,9,3277,Alexandre Lacazette,30,1928,13,12.028909,2,2.209213,45,22,3,0,F M S,Arsenal,10,9.745403,14.361542,2.937941

In [11]:
# Pemain dengan assist terbanyak

df.sort_values(by='assists', ascending=False).head(10)

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
58,58,447,Kevin De Bruyne,24,1918,5,9.908440,11,10.003763,79,72,1,0,M S,Manchester City,3,7.624933,21.079132,10.636448
51,51,675,Jack Grealish,26,2187,6,5.192684,10,9.334137,50,81,5,0,F M S,Aston Villa,6,5.192684,17.487469,6.972044
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
6,6,755,Jamie Vardy,34,2848,15,19.942946,9,5.087882,82,28,1,0,F S,Leicester,7,13.092427,18.227907,2.412588
57,57,8026,Raphinha,30,2369,6,6.219143,9,9.524861,67,65,3,0,M S,Leeds,6,6.219143,16.792778,6.679692
15,15,556,Marcus Rashford,37,2941,11,9.579710,9,4.185122,79,44,4,0,F M S,Manchester United,11,9.579710,20.441910,8.927208
41,41,8720,Jack Harrison,36,2871,8,6.254043,8,7.523059,46,59,2,0,M S,Leeds,8,6.254043,19.397490,8.035575
281,281,534,Aaron Cresswell,35,3086,0,0.883464,8,7.347331,19,57,3,0,D,West Ham,0,0.883464,10.609667,8.381824

In [12]:
# Rata-rata gol

df['goals'].mean()

np.float64(1.8620689655172413)

In [13]:
# Total gol seluruh pemain

df['goals'].sum()

np.int64(972)

In [ ]:
# Analisis Lanjutan (Menelaah Data)

# Efisiensi pemain (goals vs xG)

df['efisiensi'] = df['goals'] - df['xG']
df[['player_name', 'goals', 'xG', 'efisiensi']].sort_values(by='efisiensi', ascending=False).head(10)

# Interpretasi:
# Nilai tinggi = pemain lebih tajam dari ekspektasi
# Nilai negatif = finishing kurang bagus

          player_name  goals         xG  efisiensi
3       Son Heung-Min     17  11.023287   5.976713
17        Gareth Bale     11   5.797858   5.202142
39     James Maddison      8   3.827570   4.172430
18    Matheus Pereira     11   6.948317   4.051683
27      Jesse Lingard      9   5.095250   3.904750
12         Danny Ings     12   8.139229   3.860771
40      Stuart Dallas      8   4.457074   3.542926
8      Ilkay Gündogan     13   9.566883   3.433117
11  Kelechi Iheanacho     12   9.048596   2.951404
38        Joe Willock      8   5.088090   2.911910

In [15]:
# Kontribusi total (goal + assist)

df['kontribusi'] = df['goals'] + df['assists']
df[['player_name', 'kontribusi']].sort_values(by='kontribusi', ascending=False).head(10)

        player_name  kontribusi
0        Harry Kane          37
2   Bruno Fernandes          30
3     Son Heung-Min          27
1     Mohamed Salah          27
6       Jamie Vardy          24
4   Patrick Bamford          24
15  Marcus Rashford          20
7     Ollie Watkins          19
16       Sadio Mané          18
18  Matheus Pereira          17

In [16]:
# Pemain paling aktif (shots)

df.sort_values(by='shots', ascending=False).head(10)

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,...,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,efisiensi,kontribusi
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,...,1,0,F,Tottenham,19,19.130183,24.995648,4.451257,0.825141,37
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,...,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236,1.749153,27
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,...,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285,1.980546,30
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,...,3,0,F S,Leeds,15,16.879525,23.394953,4.131796,-1.401863,24
7,7,8865,Ollie Watkins,37,3330,14,16.280178,5,5.314029,98,...,2,1,F,Aston Villa,13,14.757840,22.014021,5.334991,-2.280178,19
16,16,838,Sadio Mané,35,2805,11,14.828548,7,7.787755,94,...,3,0,F M S,Liverpool,11,14.828548,24.998923,6.057656,-3.828548,18
26,26,482,Roberto Firmino,36,2882,9,12.860213,7,6.116863,83,...,2,0,F M S,Liverpool,9,12.860213,25.271458,10.198550,-3.860213,16
5,5,5555,Dominic Calvert-Lewin,32,2788,16,18.136449,0,2.101819,82,...,3,0,F S,Everton,16,18.136449,19.698850,4.159406,-2.136449,16
56,56,7768,Mason Mount,36,2891,6,6.884880,5,9.847691,82,...,2,0,F M S,Chelsea,5,6.123712,21.696074,12.443149,-0.884880,11
6,6,755,Jamie Vardy,34,2848,15,19.942946,9,5.087882,82,...,1,0,F S,Leicester,7,13.092427,18.227907,2.412588,-4.942946,24

In [17]:
# Analisis Berdasarkan Tim

# Rata-rata gol per tim

df.groupby('team_title')['goals'].mean().sort_values(ascending=False)

team_title
Arsenal,Newcastle United         8.000000
Manchester City                  3.208333
Everton,Southampton              3.000000
Aston Villa,Chelsea              3.000000
Liverpool,Southampton            3.000000
Tottenham                        2.750000
Leeds                            2.608696
Manchester United                2.518519
West Ham                         2.478261
Leicester                        2.370370
Liverpool                        2.370370
Chelsea                          2.240000
Aston Villa                      2.130435
Arsenal                          1.961538
Crystal Palace                   1.625000
Everton                          1.607143
Southampton                      1.555556
Brighton                         1.500000
Newcastle United                 1.384615
Burnley                          1.280000
Wolverhampton Wanderers          1.222222
West Bromwich Albion             1.178571
Chelsea,Fulham                   1.000000
Fulham                           0.925926
Sheffield United                 0.666667
Arsenal,West Bromwich Albion     0.000000
Arsenal,Brighton                 0.000000
West Bromwich Albion,West Ham    0.000000
Name: goals, dtype: float64

In [18]:
# Total gol per tim

df.groupby('team_title')['goals'].sum().sort_values(ascending=False)

team_title
Manchester City                  77
Manchester United                68
Tottenham                        66
Leicester                        64
Liverpool                        64
Leeds                            60
West Ham                         57
Chelsea                          56
Arsenal                          51
Aston Villa                      49
Everton                          45
Southampton                      42
Brighton                         39
Crystal Palace                   39
Newcastle United                 36
Wolverhampton Wanderers          33
West Bromwich Albion             33
Burnley                          32
Fulham                           25
Sheffield United                 18
Arsenal,Newcastle United          8
Everton,Southampton               3
Liverpool,Southampton             3
Aston Villa,Chelsea               3
Chelsea,Fulham                    1
Arsenal,West Bromwich Albion      0
Arsenal,Brighton                  0
West Bromwich Albion,West Ham     0
Name: goals, dtype: int64

In [19]:
# Filtering Data

# Pemain dengan gol > 15

df[df['goals'] > 15]

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,...,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,efisiensi,kontribusi
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,...,1,0,F,Tottenham,19,19.130183,24.995648,4.451257,0.825141,37
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,...,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236,1.749153,27
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,...,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285,1.980546,30
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,...,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751,5.976713,27
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,...,3,0,F S,Leeds,15,16.879525,23.394953,4.131796,-1.401863,24
5,5,5555,Dominic Calvert-Lewin,32,2788,16,18.136449,0,2.101819,82,...,3,0,F S,Everton,16,18.136449,19.698850,4.159406,-2.136449,16

In [20]:
# Pemain posisi Forward (F)

df[df['position'].str.contains('F')]

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,...,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,efisiensi,kontribusi
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,...,1,0,F,Tottenham,19,19.130183,24.995648,4.451257,0.825141,37
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,...,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236,1.749153,27
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,...,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751,5.976713,27
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,...,3,0,F S,Leeds,15,16.879525,23.394953,4.131796,-1.401863,24
5,5,5555,Dominic Calvert-Lewin,32,2788,16,18.136449,0,2.101819,82,...,3,0,F S,Everton,16,18.136449,19.698850,4.159406,-2.136449,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,344,1683,Ryan Fraser,18,920,0,0.903080,2,2.168530,13,...,0,1,F M S,Newcastle United,0,0.903080,2.994264,1.342215,-0.903080,2
353,353,1748,Lys Mousset,11,284,0,0.842632,0,0.437189,4,...,0,0,F S,Sheffield United,0,0.842632,1.540308,0.260487,-0.842632,0
380,380,4866,Aboubakar Kamara,11,303,0,0.654920,0,0.328969,4,...,1,1,F M S,Fulham,0,0.654920,1.103215,0.182326,-0.654920,0
388,388,5569,Rhian Brewster,26,1094,0,1.866453,0,1.766629,24,...,1,0,F M S,Sheffield United,0,1.866453,3.923128,0.724409,-1.866453,0
418,418,6842,Alireza Jahanbakhsh,20,466,0,1.873219,1,3.133563,18,...,3,0,D F M S,Brighton,0,1.873219,5.288836,2.521949,-1.873219,1