In [ ]:
# Import Library

import pandas as pd

In [2]:
# Load Dataset

df = pd.read_csv('Tab.csv', index_col=0)
df

       Negara  Populasi    Area    Ibukota
IN  Indonesia       250  123456    Jakarta
MA   Malaysia        25    3456         KL
SI  Singapura        15     456  Singapura
JP     Jepang        60    5678      Tokyo
TH   Thailand        45     678    Bangkok

In [4]:
# Menampilkan Informasi Dataset

df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, IN to TH
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Negara    5 non-null      str
 1   Populasi  5 non-null      int64
 2   Area      5 non-null      int64
 3   Ibukota   5 non-null      str
dtypes: int64(2), str(2)
memory usage: 200.0+ bytes

In [5]:
df.describe()

         Populasi           Area
count    5.000000       5.000000
mean    79.000000   26744.800000
std     97.172527   54105.945932
min     15.000000     456.000000
25%     25.000000     678.000000
50%     45.000000    3456.000000
75%     60.000000    5678.000000
max    250.000000  123456.000000

In [6]:
df.columns

Index(['Negara', 'Populasi', 'Area', 'Ibukota'], dtype='str')

In [ ]:
# Menampilkan kolom Negara

df['Negara']

IN    Indonesia
MA     Malaysia
SI    Singapura
JP       Jepang
TH     Thailand
Name: Negara, dtype: str

In [8]:
# Menampilkan beberapa kolom

df[['Negara', 'Populasi']]

       Negara  Populasi
IN  Indonesia       250
MA   Malaysia        25
SI  Singapura        15
JP     Jepang        60
TH   Thailand        45

In [9]:
# Negara dengan populasi lebih dari 30

df[df['Populasi'] > 30]

       Negara  Populasi    Area  Ibukota
IN  Indonesia       250  123456  Jakarta
JP     Jepang        60    5678    Tokyo
TH   Thailand        45     678  Bangkok

In [10]:
# Menghitung kepadatan penduduk

df['Kepadatan'] = df['Populasi'] / df['Area']
df

       Negara  Populasi    Area    Ibukota  Kepadatan
IN  Indonesia       250  123456    Jakarta   0.002025
MA   Malaysia        25    3456         KL   0.007234
SI  Singapura        15     456  Singapura   0.032895
JP     Jepang        60    5678      Tokyo   0.010567
TH   Thailand        45     678    Bangkok   0.066372

In [11]:
# Urutkan berdasarkan populasi terbesar

df.sort_values(by='Populasi', ascending=False)

       Negara  Populasi    Area    Ibukota  Kepadatan
IN  Indonesia       250  123456    Jakarta   0.002025
JP     Jepang        60    5678      Tokyo   0.010567
TH   Thailand        45     678    Bangkok   0.066372
MA   Malaysia        25    3456         KL   0.007234
SI  Singapura        15     456  Singapura   0.032895

In [18]:
# Rata-rata populasi

print("Rata-rata populasi:", df['Populasi'].mean())

Rata-rata populasi: 79.0

In [19]:
# Total populasi


print("Total populasi:", df['Populasi'].sum())

Total populasi: 395

In [ ]:
# Ubah nama ibukota Malaysia

df.loc['MA', 'Ibukota'] = 'Kuala Lumpur'
df

       Negara  Populasi    Area       Ibukota  Kepadatan
IN  Indonesia       250  123456       Jakarta   0.002025
MA   Malaysia        25    3456  Kuala Lumpur   0.007234
SI  Singapura        15     456     Singapura   0.032895
JP     Jepang        60    5678         Tokyo   0.010567
TH   Thailand        45     678       Bangkok   0.066372